apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnt-farmacias-be
spec:
  selector:
    matchLabels:
      app: farmacias-be
  replicas: 2
  template:
    metadata:
      labels:
        app: farmacias-be
    spec:
      containers:
      - name: farmacias-be
        image: us.gcr.io/sandbox-1573607247877/be-buscar-farmacias:v0.0.7
        env:
        - name: APP_SETTINGS
          value: config.DevelopmentConfig
        - name: FLASK_ENV
          value: development
        ports:
        - containerPort: 5000